name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
   
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: "Header"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
         
         # plugin_stackoverflow: yes
         # plugin_stackoverflow_user: 13961578                           # Stackoverflow user id (required)
         # plugin_stackoverflow_sections: answers-top, questions-recent # Display top answers and recent questions
         # plugin_stackoverflow_limit: 2                                # Display 2 entries per section
         # plugin_stackoverflow_lines: 4                                # Display 4 lines per entry
          
          extras_css: | 
            h1, h2, h3 {
             color: #663399;
            }

            
          
